[config]
schemaVersion = "0.0.1"

[package]
namespace = "Restless"
name = "RestlessCook"
versionNumber = "0.1.9"
description = "Cook the haul, make meals, turn meals into feasts. Meadows through Ashlands. Needs RestlessCore."
websiteUrl = "https://github.com/factoryblack/RestlessValheim"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2350"
ValheimModding-Jotunn = "2.30.1"
Restless-RestlessCore = "0.1.9"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../../artifacts/tcli-cook"

[[build.copy]]
source = "../../dist/RestlessCook.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../art/cook/runtime"
target = "mesh"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]

[publish.categories]
valheim = ["crafting", "tweaks", "mods"]
