using System.Globalization;
using RestlessQoL.Storage;
using UnityEngine;
void Check(bool condition,string name){if(!condition)throw new Exception(name);Console.WriteLine("PASS "+name);}
var item=new ItemDrop.ItemData{m_durability=12.5f,m_customData=new(){{"x","y"}}};
string? key=null;
foreach(var culture in new[]{"en-US","de-DE","fr-FR","ar-SA"}){CultureInfo.CurrentCulture=CultureInfo.GetCultureInfo(culture);var current=ItemKey.Of(item);key??=current;Check(key==current,"item identity across "+culture);}
var ward=new PrivateArea{m_piece=new(){Creator=11}};PrivateArea.m_allAreas.Add(ward);
Check(!StorageAccess.Allows(new(),22),"ward rejects another actor");
Check(StorageAccess.Allows(new(),11),"ward permits creator");ward.Permitted.Add(22);
Check(StorageAccess.Allows(new(),22),"ward permits invited actor");
Check(!StorageAccess.Allows(new(),0),"background actor cannot bypass a ward");
PrivateArea.m_allAreas.Add(new(){m_piece=new(){Creator=99}});
Check(StorageAccess.Allows(new(),22),"overlapping wards match native access");
ward.Enabled=false;Check(!StorageAccess.Allows(new(),22),"permission change is rechecked");PrivateArea.m_allAreas.Clear();
Check(StorageAccess.Allows(new(),0),"unwarded background store remains available");
var player=new Player{Id=22};Player.m_localPlayer=player;
Check(StorageAccess.UsesBag(player,22,new(),10),"matching nearby order can pay from bag");
Check(!StorageAccess.UsesBag(player,11,new(),10),"ownership change cannot spend another bag");
Check(!StorageAccess.UsesBag(player,0,new(),10),"anonymous automation cannot spend local bag");
player.transform.position=new(11);Check(!StorageAccess.UsesBag(player,22,new(),10),"distant bag is excluded");
Check(StorageAccess.Reach(20,5)==5&&StorageAccess.Reach(5,20)==5&&StorageAccess.Reach(-1,5)==0,"range intersection never widens either setting");
WorksHarness.Current=new();WorksHarness.Planned.Clear();WorksHarness.Paid.Clear();
WorksHarness.Current.Orders.Add(new(){PlayerId=11,Count=1});WorksHarness.Current.Orders.Add(new(){PlayerId=22,Count=1});
WorksHarness.Tick(new(),new());Check(WorksHarness.Paid.SequenceEqual(new long[]{11,22}),"actual workshop tick pays each order's actor");Check(WorksHarness.Planned.SequenceEqual(new long[]{11,22}),"actual workshop tick plans each order's actor");
CookHarness.Current=new();CookHarness.Planned.Clear();CookHarness.Paid.Clear();
CookHarness.Current.Orders.Add(new(){PlayerId=11});CookHarness.Current.Orders.Add(new(){PlayerId=22});
CookHarness.Tick(new(),1);Check(CookHarness.Planned.SequenceEqual(new long[]{11,22})&&CookHarness.Paid.SequenceEqual(new long[]{11,22}),"actual kitchen tick uses matching plan and payment actors");
ZNetScene.instance=new();PlantHarness.Tick();
var grown=new GameObject{name="Pickable_Carrot"};var seed=new GameObject{name="carrot"};var piece=seed.Add(new Piece());seed.Add(new Plant{m_grownPrefabs=new[]{grown}});ZNetScene.instance.m_prefabs.Add(seed);
var ripe=new GameObject{name=grown.name}.Add(new Pickable());
Check(PlantHarness.SeedFor(ripe)==piece,"legacy grown crop resolves without Piece or Plant");
PlantHarness.AfterPick(ripe,player,true);Check(player.Planted==piece&&player.Paid==1,"one-shot harvest replants correct seed and pays once");
player.Planted=null;player.Paid=0;ripe.m_respawnTimeMinutes=10;PlantHarness.AfterPick(ripe,player,true);Check(player.Planted==null&&player.Paid==0,"regrowing forage is not replanted");
ripe.m_respawnTimeMinutes=0;player.CanPay=false;PlantHarness.AfterPick(ripe,player,true);Check(player.Planted==null&&player.Paid==0,"insufficient seeds do not place or spend");
var modSeed=new GameObject{name="modseed"};var modPiece=modSeed.Add(new Piece());ZNetScene.instance.m_prefabs.Add(modSeed);ripe.m_nview.Data.Data["RestlessReplant"]="modseed";Check(PlantHarness.SeedFor(ripe)==modPiece,"saved sapling identity overrides legacy discovery");
var live=new ItemDrop();var gone=new ItemDrop();gone.m_nview.Valid=false;PlantHarness.PickedDrops[new(1)]=live;PlantHarness.PickedDrops[new(2)]=gone;Time.unscaledTime=3;PlantHarness.Tick();Check(PlantHarness.PickedDrops.Count==1,"pickup history retains live drop and prunes destroyed drops");
ZNetScene.instance=new();PlantHarness.Tick();Check(PlantHarness.PickedDrops.Count==0&&PlantHarness.SeedFor(new GameObject{name=grown.name}.Add(new Pickable()))==null,"world change clears pickup history and sapling cache");
player.transform.position=new();player.Bag=new();
var box=new PileBox();PileBox.All.Add(box);NearbyStorage.EnsureDropPrefab(box.Item);var pileKey=ItemKey.Of(box.Item);
ward=new(){m_piece=new(){Creator=11}};PrivateArea.m_allAreas.Add(ward);
var lots=new List<NearbyLot>();PileHarness.List(new(),20,22,lots);var taken=-1;PileHarness.Take(player,pileKey,4,n=>taken=n);
Check(lots.Count==0&&taken==0&&PileHarness.CountNearby("material")==0&&PileHarness.ConsumeNearby("material",4)==0&&PileHarness.Drain(new(),20,22,"material",4)==0&&box.Stored==10&&Pile.Claims==0,"actual pile search, take and crafting reject ward access before claiming");
ward.Permitted.Add(22);PileHarness.Take(player,pileKey,4,n=>taken=n);Check(taken==4&&box.Stored==6&&player.Bag.Items.Sum(i=>i.m_stack)==4,"permitted pile transfer conserves items");
box.Stored=10;box.transform.position=new(8);lots.Clear();PileHarness.List(new(),20,22,lots);PileHarness.Take(player,pileKey,4,n=>taken=n);Check(lots.Count==0&&taken==0&&box.Stored==10,"actual browser listing and withdrawal share isolated pile range");
box.transform.position=new();Pile.Delay=true;PileHarness.Take(player,pileKey,4,n=>taken=n);ward.Permitted.Clear();foreach(var action in Pile.Pending)action();Check(taken==0&&box.Stored==10,"delayed ownership callback rechecks permission before adding items");Pile.Pending.Clear();Pile.Delay=false;
Console.WriteLine("Audit regressions passed.");
