[config]
schemaVersion = "0.0.1"

[package]
namespace = "Restless"
name = "RestlessPlant"
versionNumber = "0.2.2"
description = "Grow berries, mushrooms and more. Plant aligned rows, harvest nearby crops and replant as you go."
websiteUrl = "https://github.com/factoryblack/RestlessValheim/blob/main/docs/player/plant.md"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2351"
ValheimModding-Jotunn = "2.30.2"
Restless-RestlessCore = "0.2.6"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../../artifacts/tcli-plant"

[[build.copy]]
source = "../../dist/RestlessPlant.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]

[publish.categories]
valheim = ["misc", "tweaks", "mods"]

