<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>RestlessCore</AssemblyName>
    <RootNamespace>RestlessQoL</RootNamespace>
    <Version>0.1.11</Version>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(MSBuildThisFileDirectory)..\..\dist\</OutputPath>
    <DebugType>embedded</DebugType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JotunnLib" Version="2.30.1" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ValheimManaged)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>$(ValheimManaged)\com.rlabrecque.steamworks.net.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\*.png" LogicalName="RestlessQoL.Assets.%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="RestlessPiles" />
  </ItemGroup>
</Project>
