[config]
schemaVersion = "0.0.1"

[package]
namespace = "Restless"
name = "Restless_Valheim"
versionNumber = "0.1.15"
description = "Restless Valheim: BepInEx, Jötunn, RestlessCore, RestlessCook, RestlessPiles, and RestlessPlant."
websiteUrl = "https://github.com/factoryblack/RestlessValheim"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2350"
ValheimModding-Jotunn = "2.30.2"
Restless-RestlessCore = "0.1.11"
Restless-RestlessCook = "0.1.9"
Restless-RestlessPiles = "0.1.4"
Restless-RestlessPlant = "0.1.4"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../../artifacts/tcli-pack"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]

[publish.categories]
valheim = ["modpacks"]
