[config]
schemaVersion = "0.0.1"

[package]
namespace = "Restless"
name = "Restless_Valheim"
versionNumber = "0.1.23"
description = "Restless Valheim: BepInEx, Jötunn, RestlessCore, RestlessCook, RestlessPiles, RestlessPlant, RestlessDrawers, and RestlessStorage."
websiteUrl = "https://github.com/factoryblack/RestlessValheim"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2351"
ValheimModding-Jotunn = "2.30.2"
Restless-RestlessCore = "0.1.19"
Restless-RestlessCook = "0.1.10"
Restless-RestlessPiles = "0.1.8"
Restless-RestlessPlant = "0.1.8"
Restless-RestlessDrawers = "0.1.2"
Restless-RestlessStorage = "0.1.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../../artifacts/tcli-pack"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]

[publish.categories]
valheim = ["modpacks"]
