[config]
schemaVersion = "0.0.1"

[package]
namespace = "Restless"
name = "RestlessPiles"
versionNumber = "0.2.1"
description = "Turn familiar resource piles into bulk storage. Deposit supplies, take a stack and craft from nearby piles."
websiteUrl = "https://github.com/factoryblack/RestlessValheim/blob/main/docs/player/piles.md"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2351"
ValheimModding-Jotunn = "2.30.2"
Restless-RestlessCore = "0.2.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../../artifacts/tcli-piles"

[[build.copy]]
source = "../../dist/RestlessPiles.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]

[publish.categories]
valheim = ["tweaks", "misc", "mods"]

