namespace RestlessQoL.Core;

// Generated by scripts/sync-versions.py from versions.yaml. Do not edit.
internal static class VersionPins
{
    public const string BepInEx = "5.4.2351";
    public const string Jotunn = "2.30.2";
    public const string Core = "0.2.4";
    public const string Cook = "0.5.0";
    public const string Piles = "0.2.1";
    public const string Plant = "0.2.2";
    public const string Drawers = "0.2.0";
    public const string Storage = "0.2.2";
    public const string Works = "0.1.3";

    public static string? ForGuid(string guid) => guid switch
    {
        "restless.core" => Core,
        "restless.cook" => Cook,
        "restless.piles" => Piles,
        "restless.plant" => Plant,
        "restless.drawers" => Drawers,
        "restless.storage" => Storage,
        "restless.works" => Works,
        _ => null
    };
}
