namespace RestlessQoL.Core;

// Generated by scripts/sync-versions.py from versions.yaml. Do not edit.
internal static class VersionPins
{
    public const string BepInEx = "5.4.2351";
    public const string Jotunn = "2.30.2";
    public const string Core = "0.1.16";
    public const string Cook = "0.1.9";
    public const string Piles = "0.1.6";
    public const string Plant = "0.1.6";
    public const string Drawers = "0.1.1";

    public static string? ForGuid(string guid) => guid switch
    {
        "restless.core" => Core,
        "restless.cook" => Cook,
        "restless.piles" => Piles,
        "restless.plant" => Plant,
        "restless.drawers" => Drawers,
        _ => null
    };
}
